apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    hmc.mirantis.com/managed: "true"
  name: capi
  namespace: hmc-system
spec:
  chartRef:
    kind: HelmChart
    name: cluster-api-0-0-3
    namespace: hmc-system
  dependsOn:
    - name: hmc
  install: {}
  interval: 10m0s
  releaseName: capi
