apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  finalizers:
  - finalizers.fluxcd.io
  labels:
    hmc.mirantis.com/managed: "true"
  name: k0smotron
  namespace: hmc-system
spec:
  chartRef:
    kind: HelmChart
    name: k0smotron-0-0-3
    namespace: hmc-system
  dependsOn:
    - name: capi
  install: {}
  interval: 10m0s
  releaseName: k0smotron
