---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: azure-cluster-identity
  namespace: hmc-system
spec:
  allowedNamespaces: {}
  clientID: 12345678-959b-481f-b094-eb043a87570a # change this
  clientSecret:
    name: azure-cluster-identity-secret
    namespace: hmc-system
  tenantID: 12345678-959b-481f-b094-eb043a87570a # change this
  type: ServicePrincipal
