---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: aws-credential-cluster-1
spec:
  description: "Basic AWS credentials"
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSClusterStaticIdentity
    name: aws-cluster-identity-1
