---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: default
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: "v1.16.2"
  interval: 1h0m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
