---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  labels:
    hmc.mirantis.com/managed: "true"
  name: projectsveltos-0-42-0
  namespace: hmc-system
spec:
  chart: projectsveltos
  interval: 10m0s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: hmc-templates
  version: 0.42.0
