apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterStaticIdentity
metadata:
  name: aws-cluster-identity
  namespace: hmc-system
spec:
  secretRef: aws-cluster-identity-secret
  allowedNamespaces: {}
