---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: ManagedCluster
    patch: |-
      - op: add
        path: /spec/services
        value:
          - template: kyverno
            name: kyverno
            namespace: kyverno
