---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  labels:
    hmc.mirantis.com/managed: "true"
  name: hmc-0-0-4-tpl
  namespace: hmc-system
spec:
  chart: hmc-templates
  interval: 10m0s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: hmc-templates
  version: 0.0.4
