---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    hmc.mirantis.com/managed: "true"
  name: hmc-0-0-4-tpl
  namespace: hmc-system
spec:
  chartRef:
    kind: HelmChart
    name: hmc-0-0-4-tpl
    namespace: hmc-system
  install: {}
  interval: 10m0s
  releaseName: hmc-0-0-4-tpl
  values:
    createRelease: true
