---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: hmc
  namespace: default
spec:
  interval: 5m0s
  url: oci://ghcr.io/mirantis/hmc/charts/hmc
  ref:
    tag: 0.0.4
