---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hmc
spec:
  chartRef:
    kind: HelmRepository
    name: hmc-templates
  targetNamespace: hmc-system
  interval: 10m
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
