---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hmc
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: hmc
    namespace: default
  targetNamespace: hmc-system
  interval: 10m
  values:
    flux2:
      enabled: false
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
