---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - networkpolicy.yaml
patches:
  - target:
      kind: NetworkPolicy
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: flux-system
