---
apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: managed-standalone-cluster
spec:
  template: aws-standalone-cp-0-0-3
  credential: aws-credential
  dryRun: false
  config:
    region: us-east-1
    controlPlaneNumber: 3
    controlPlane:
      instanceType: t3.small
    workersNumber: 5
    worker:
      instanceType: t3.small
