---
apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: soeren-cluster-aws-2
spec:
  template: aws-standalone-cp-0-0-3
  credential: aws-credential-cluster-1
  dryRun: false
  config:
    region: us-east-1
    controlPlaneNumber: 3
    controlPlane:
      instanceType: t3.small
    workersNumber: 2
    worker:
      instanceType: t3.small
