---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - ../generic
patches:
  - target:
      kind: ManagedCluster
    patch: |-
      - op: replace # default template
        path: /spec/template
        value: "azure-standalone-cp-0-0-3"
      - op: replace # default baseline config
        path: /spec/config
        value:
          location: "germanywestcentral" # change this
          subscriptionID: "12345678-1234-5678-1234-567812345678" # change this
          controlPlane:
            vmSize: Standard_A4_v2
          worker:
            vmSize: Standard_A4_v2
