---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: hmc-system
resources:
  - ../../../../managed-clusters/aws
  - credential.yaml
  - static-identity.yaml
patches:
  - target:
      kind: ManagedCluster
    patch: |-
      - op: replace
        path: /metadata/name
        value: "soeren-cluster-1"
      - op: replace
        path: /spec/credential
        value: "aws-credential-cluster-1"
      - op: replace
        path: /spec/config/workersNumber
        value: 3
      - op: replace
        path: /spec/config/worker/instanceType
        value: t3.medium
