---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: ManagedCluster
    patch: |-
      - op: add
        path: /spec/services
        value:
          - template: ingress-nginx-4-11-3
            name: ingress-nginx
            namespace: ingress-nginx
