---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 2a
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/soerenschneider/hmc-test.git
